apiVersion: v1
kind: Secret
metadata:
  name: gpe-mariadb-secret
  namespace: gpe
  labels:
    k8s.mariadb.com/watch: ""
type: Opaque
stringData:
  root-password: "030GwflhSg8oeC4PPjRnUTLezQ5Mkknc"
  user-password: "4AuSP1OSI75lMJ9NC5owv31X8GptuPuT"
  replication-password: "1xgZZeFXx6wafxYSFEnUq72otKAYbUEA"