apiVersion: v1
kind: Secret
metadata:
  name: gpe-mariadb-secret
  namespace: gpe
type: Opaque
stringData:
  root-password: 030GwflhSg8oeC4PPjRnUTLezQ5Mkknc
  user-password: azerty1234
  replication-password: 1xgZZeFXx6wafxYSFEnUq72otKAYbUEA