apiVersion: v1
kind: Secret
metadata:
  name: gpe-secrets
  namespace: gpe
type: Opaque
stringData:
  DB_USER: "gpe-user"
  DB_PASSWORD: "azerty1234"
  DB_HOST: "my-mariadb-primary"
  DB_PORT: "3306"
  DB_NAME: "gpe-db"