apiVersion: v1
kind: Secret
metadata:
  name: gpe-secrets
type: Opaque
stringData:
  DB_USER: gpe-user
  DB_PASSWORD: 4AuSP1OSI75lMJ9NC5owv31X8GptuPuT
  DB_HOST: my-mariadb-primary
  DB_PORT: 3306
  DB_NAME: gpe-db